#!/usr/bin/env bash

CANISTER=ic-solana-provider
CANISTER_WASM=target/wasm32-unknown-unknown/release/$(echo $CANISTER | tr '-' '_').wasm

# Build the canister
cargo build --release --target wasm32-unknown-unknown --package $CANISTER

# Extract the did file
candid-extractor $CANISTER_WASM > ./src/$CANISTER/$CANISTER.did

# optimize wasm file
# ic-wasm $CANISTER_WASM -o $CANISTER_WASM metadata candid:service -f $DID_PATH -v public

gzip --no-name --force $CANISTER_WASM
cp $CANISTER_WASM.gz ./src/$CANISTER/$CANISTER.wasm.gz

# Deploy schnorr canister
dfx deploy schnorr_canister

# Get the canister id
SCHNORR_CANISTER_ID=$(dfx canister id schnorr_canister)

echo "Schnorr canister id: $CANISTER_ID"

# Deploy the solana canister and set the schnorr canister id
SOLANA_RPC_URL="https://solana-devnet.g.alchemy.com/v2/ClRAj3-CPTvcl7CljBv-fdtwhVK-XWYQ"
# SOLANA_RPC_URL="testnet"
dfx deploy ic-solana-provider --argument "( record { 
    rpc_url = opt \"${SOLANA_RPC_URL}\"; 
    nodesInSubnet = 28; 
    schnorr_canister = opt \"${SCHNORR_CANISTER_ID}\";
    schnorr_key_name = null;
    })" \
    --mode=reinstall -y

# Get the canister id
CANISTER_ID=$(dfx canister id ic-solana-provider)

echo "Solana canister id: $CANISTER_ID"

# Deploy the test canister
CANISTER=test_canister
CANISTER_WASM=target/wasm32-unknown-unknown/release/$(echo $CANISTER | tr '-' '_').wasm

# Extract the did file
candid-extractor $CANISTER_WASM > ./src/$CANISTER/$CANISTER.did

dfx deploy test_canister --argument "( \"${CANISTER_ID}\", \"${SCHNORR_CANISTER_ID}\")" --mode=reinstall -y

echo "Test canister id: $CANISTER_ID"

echo "Done"
